spring:
  application:
    name: rabbitmq-trials
  rabbitmq:
    host: localhost
    port: 5672
    username: dev
    password: dev
server:
  port: 5000
rabbitmq:
  queueName: firstQueue
  exchangeName: firstExchange
  routingKeyName: firstRoutingKey
